### PR TITLE
Handle RegExp patterns more expectedly

### LINKED ISSUE #12: Support RegEx for Numbers
Actual:

``` js
{
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '64.99.80.121',
  port: 443
}
```

Expected:

``` js
{
    address: /\w+/,
    code: /\w+/,
    errno: /\w+/,
    port: /\d+/,
    syscall: /\w+/
}
```

Result:

```
TMATCH object { address: /\w+/,
  code: /\w+/,
  errno: /\w+/,
  port: /\d+/,
  syscall: /\w+/ }
TMATCH object~=object test
  TMATCH patternkeys=["address","code","errno","port","syscall"] objkeys=["code","errno","syscall","address","port"]
  TMATCH check seen objects...
  TMATCH not seen previously
  TMATCH test obj["syscall"] connect /\w+/
TMATCH string /\w+/
TMATCH string~=regexp test
  TMATCH test obj["port"] 443 /\d+/
TMATCH number /\d+/
TMATCH obj is not object, pattern is not object, false
```

### PR DESCRIPTION
**Pull request by isaacs**
Close #12

Breaking change.

cc @addaleax @dotnetCarpenter

### CODE REVIEW

**Review by addaleax — APPROVED** [review]

**Comment by addaleax** [comment]
Thanks for looking into this! fwiw, I had already PRed at https://github.com/tapjs/tmatch/pull/14, but this seems to work just as well. :+1:

**Comment by isaacs** [comment]
Ah, sorry, I had missed #13 and #14 in the flood of green keeping.

Had to add a little bit of extra to get 100% test coverage on 0.10.

**Comment by dotnetCarpenter** [comment]
@isaacs This PR passes 62aaf8ae62b36fd63e623fe175720760d4fb1287 - which is the main fix in #13

**Comment by addaleax** [comment]
Yea, don’t worry about it – merge whichever you prefer :)

**Pull request merged**
